- name: install container
  docker_container:
    name: jenkins
    image: jenkinsci/blueocean
    detach: yes
    groups:
      - 998
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
  tags: [jenkins]

- name: inspect volume
  shell: docker volume inspect jenkins-data
  register: vol_res
  tags: [vol]

- name: install jmespath for json_query
  pip:
    name: jmespath
    state: present

- name: set fact
  set_fact: vole={{vol_res.stdout | from_json | json_query('[0].Mountpoint')}}
  tags: [vol]

- name: list volume
  find:
    paths: "{{vole}}"
  register: bla
  tags: [vol]

# - name: print volume files
#   debug:
#     msg: "{{bla}}"
#   tags: [vol]
