nexus:
  enabled: false
nexusServiceLink:
  enabled: true
  externalName: "nexus.10.100.198.200.nip.io"
chartmuseum:
  enabled: false
chartmuseumServiceLink:
  enabled: true
  externalName: "chartmuseum.10.100.198.200.nip.io"
