- name: install
  docker_container:
    name: registry
    image: registry:2
    detach: yes
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    restart_policy: always
  tags: [registry]
