- name: create temp dir
  file:
    path: "{{jenkinsMasterTmpDir}}"
    state: directory
  tags: [jenkins-master]

- name: template dockerfile
  template:
    src: Dockerfile
    dest: "{{jenkinsMasterTmpDir}}/Dockerfile"
  tags: [jenkins-master]

- name: copy dockerfile context
  copy:
    src: "{{item.src}}"
    dest: "{{jenkinsMasterTmpDir}}/{{item.dest}}"
  loop:
    - { src: 'executors.groovy', dest: 'executors.groovy' }
    - { src: 'default-user.groovy', dest: 'default-user.groovy' }
  tags: [jenkins-master]

- name: build docker image
  docker_image:
    name: jenkins-master
    path: "{{jenkinsMasterTmpDir}}"
  register: jenkinsMasterBuildImageRes
  tags: [jenkins-master]

- name: get docker group id
  import_role:
    name: system
    tasks_from: groupid
  vars:
    groupName: docker
    groupVar: dockerGroupId
  tags: [jenkins-master]

- name: install container
  docker_container:
    name: jenkins-master
    image: jenkins-master
    detach: yes
    groups:
      - "{{dockerGroupId}}"
    ports:
      - 8080:8080
    volumes:
      - jenkins-master-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always
  tags: [jenkins-master]

- name: get container volume mount path
  import_role:
    name: docker
    tasks_from: volume
  vars:
    volumeName: jenkins-master-data
    volumeVar: jenkinsVolumePath
  tags: [jenkins-master]

- name: wait for jenkins
  uri:
    url: "http://10.100.198.200:8080"
    method: POST
    user: "{{jenkinsAdminUser}}"
    password: "{{jenkinsAdminPassword}}"
    force_basic_auth: yes
  register: result
  until: result.status == 200
  retries: 10
  delay: 5
  tags: [jenkins-master]

- name: install plugins
  uri:
    url: http://10.100.198.200:8080/pluginManager/installNecessaryPlugins
    method: POST
    user: "{{jenkinsAdminUser}}"
    password: "{{jenkinsAdminPassword}}"
    force_basic_auth: yes
    headers:
      Content-Type: text/xml
    body: '<jenkins><install plugin="{{item}}@latest" /></jenkins>'
    status_code: 200,302
    creates: "{{jenkinsVolumePath}}/plugins/{{item}}"
  loop:
    - blueocean
    - workflow-aggregator
    - ws-cleanup
    - build-pipeline-plugin
    - matrix-auth
    - pam-auth
    - antisamy-markup-formatter
    - xunit
    - timestamper
    - build-timeout
    - ssh-slaves
  tags: [jenkins-master]

- name: wait for plugins
  wait_for:
    path: "{{jenkinsVolumePath}}/plugins/{{item}}"
  loop:
    - blueocean
    - workflow-aggregator
    - ws-cleanup
    - build-pipeline-plugin
    - matrix-auth
    - pam-auth
    - antisamy-markup-formatter
    - xunit
    - timestamper
    - build-timeout
    - ssh-slaves
  tags: [jenkins-master]

- name: setup credentials
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0777
  loop:
    - { src: "credentials.xml", dest: "{{jenkinsVolumePath}}/"}
  tags: [jenkins-master]

- name: setup nodes
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0777
    directory_mode: 0777
  loop:
    - { src: "nodes/docker1/config.xml", dest: "{{jenkinsVolumePath}}/nodes/docker1/"}
    - { src: "nodes/docker2/config.xml", dest: "{{jenkinsVolumePath}}/nodes/docker2/"}
  tags: [jenkins-master]

- name: setup shared libraries
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0777
  loop:
    - { src: "org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml", dest: "{{jenkinsVolumePath}}/" }
  tags: [jenkins-master]

- name: setup jobs
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0777
    directory_mode: 0777
  loop:
    - { src: "jobs/frontend/config.xml", dest: "{{jenkinsVolumePath}}/jobs/frontend/" }
  tags: [jenkins-master]

- name: reload server
  uri:
    url: http://10.100.198.200:8080/reload
    method: POST
    user: "{{jenkinsAdminUser}}"
    password: "{{jenkinsAdminPassword}}"
    force_basic_auth: yes
    status_code: 200,302
  register: result
  until: result.status == 200 or result.status == 302
  retries: 10
  delay: 5
  tags: [jenkins-master]
