restartJenkinsEvent: "restart jenkins master"

dockerfileContext:
  - executors.groovy
  - default-user.groovy

plugins:
  - blueocean
  - workflow-aggregator
  - ws-cleanup
  - build-pipeline-plugin
  - matrix-auth
  - pam-auth
  - antisamy-markup-formatter
  - xunit
  - timestamper
  - build-timeout
  - ssh-slaves

templates:
  - { src: "credentials.xml", dest: "{{jenkinsVolumePath}}/" }
  - { src: "nodes/docker1/config.xml", dest: "{{jenkinsVolumePath}}/nodes/docker1/" }
  - { src: "nodes/docker2/config.xml", dest: "{{jenkinsVolumePath}}/nodes/docker2/" }

files:
  - { src: "org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml", dest: "{{jenkinsVolumePath}}/" }
  - { src: "jobs/frontend/config.xml", dest: "{{jenkinsVolumePath}}/jobs/frontend/" }
