- name: uninstall old components
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
  tags: [docker]

- name: update repo
  apt:
    update_cache: yes
  tags: [docker]

- name: install ca
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ca-certificates
  tags: [docker]

- name: get repo key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    state: present
  tags: [docker]

- name: add repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
    update_cache: yes
  tags: [docker]

- name: install components
  apt:
    name: "{{ packages }}"
    state: latest   
  vars:
    packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  tags: [docker]

- name: install sdk for python
  pip:
    name: docker
    state: present
  tags: [docker]

- name: copy config
  copy:
    src: "{{ docker_cfg_src }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_docker_config
  tags: [docker]

- name: add vagrant to docker group
  user:
    name: vagrant
    groups:
      - docker
  register: add_vagrant_to_docker
  tags: [docker]

- name: restart deamon
  service:
    name: docker
    state: restarted
  when: copy_docker_config is changed or add_vagrant_to_docker is changed
  tags: [docker]
