- hosts: all
  remote_user: vagrant
  become: true
  pre_tasks:
    - import_role: 
        name: system
        tasks_from: timedate
    - import_role: 
        name: system
        tasks_from: hosts
  roles:
    - powershell
    - docker
    - docker-compose
    - registry
    - portainer
    - jenkins-master
    - jenkins-slave
