- hosts: localhost
  connection: local
  remote_user: vagrant
  become: true
  roles:
    - ansible

- hosts: localhost
  connection: local
  remote_user: vagrant
  become: true
  roles:
    # - powershell
    # - docker
    # - docker-compose
    # - registry
    # - portainer
    - jenkins-master
    # - jenkins-slave