- hosts: localhost
  connection: local
  remote_user: vagrant
  become: true
  roles:
    - ansible
    - powershell
    - docker
    - docker-compose
    - registry
    - portainer
    - jenkins
    - jenkins-slave