apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
  namespace: {{nfsClientNamespace}}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: {{nfsClientNamespace}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: {{nfsProvisionerName}}
            - name: NFS_SERVER
              value: "{{nfsServer}}"
            - name: NFS_PATH
              value: "{{nfsExportedPath}}"
      volumes:
        - name: nfs-client-root
          nfs:
            server: "{{nfsServer}}"
            path: "{{nfsExportedPath}}"
