- name: .kube directory exists
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
  tags: [k8s-master]

- name: copy config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant
  tags: [k8s-master]

- name: get calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.7/manifests/calico.yaml
    dest: /tmp/calico_manifest.yml
  tags: [k8s-master]

- name: adjust calico manifest
  replace:
    path: /tmp/calico_manifest.yml
    regexp: '192.168.0.0/16'
    replace: '{{network_cidr}}'
  tags: [k8s-master]

- name: setup calico
  shell: kubectl apply -f /tmp/calico_manifest.yml
  become: yes
  become_user: vagrant
  tags: [k8s-master]
